name = "CANTools"
uuid = "c60dd3e6-0606-41cb-8b3c-18d234524e82"
authors = ["Tim Lucas Sabelmann"]
version = "1.0.0"

[compat]
julia = "1.5.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
