name = "CANalyze"
uuid = "2dc4fe6c-d2be-46ad-ace5-0bbcd4825534"
authors = ["Tim Lucas Sabelmann"]
version = "1.4.0"

[compat]
julia = "1.5.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
